export let playerNames = ["Letters",
  "One",
  "Devil Soul",
  "BAD BOY",
  "Call Of Duty",
  "Tik Tok",
  "Aragon",
  "Kidnapper",
  "Facebook",
  "Viking",
  "Frozen",
  "Storm",
  "STOP",
  "Happy New Year",
  "Elephant",
  "Christmas",
  "Gondal",
  "Death Slayer",
  "Deep",
  "DarK Shadow",
  "Toy Story",
  "Co Owner",
  "IOS",
  "PUBG MOBILE",
  "Deadshot Akshat",
  "Good Day",
  "End",
  "Xpointy",
  "Cobra pavan",
  "STREAMER",
  "Salazar",
  "Spirit",
  "Avenger zeus",
  "Sticker",
  "Million Roses",
  "Moderator",
  "Roses",
  "Extraction",
  "God",
  "Lingojam",
  "Happy Birthday",
  "Start",
  "Nawaf",
  "Eagle shooter",
  "Kicker",
  "Verified",
  "Camper",
  "Smoker",
  "Ultimate",
  "Superman",
  "SWAT",
  "Clan",
  "PUBG MOBILE",
  "ALOK",
  "Christmas",
  "Black soul",
  "Storm breaker",
  "Witcher",
  "Pirates",
  "Titanic",
  "Ceremony",
  "Cobra pavan",
  "Sticker",
  "SAVAGE",
  "Titanium",
  "MAMY",
  "The BOSS",
  "ZEUS",
  "Nemo",
  "Dark Siders",
  "Symbol",
  "Sonic",
  "Deadshot Akshat",
  "Warriors",
  "Dark soul",
  "Poison",
  "Race",
  "God",
  "CRIMINAL",
  "Storm",
  "Mafia",
  "Relax",
  "Eternal",
  "CRAZY",
  "Merci",
  "Brand",
  "Titanic",
  "Android",
  "Elephant",
  "White Walker",
  "Start",
  "NOOB",
  "Furious",
  "Agent 47",
  "SAFAH",
  "Time",
  "Toy Story",
  "Million Roses",
  "IOS",
  "Big boss",
  "Wedding",
  "Devil",
  "Zpointy",
  "Hero prince",
  "Heidern",
  "Wizard",
  "Fury",
  "Crusher",
  "Chaser",
  "Thor",
  "Mafia",
  "Cobra pavan",
  "VIP Gamers",
  "Ideas",
  "Dark Siders",
  "UNKNOWN",
  "Virus",
  "Venom",
  "Mom",
  "General",
  "MAMY"
]

export let serverNames = ["Giant Factions",
  "Combat Nation",
  "Spartan Warzone",
  "Destroy Build",
  "Spooky sVanilla",
  "Storm Roleplay",
  "Dusk Worlds",
  "Hero Factions",
  "1337 Factions",
  "Raiding Economy",
  "Storm Mining",
  "Infinite Hardcore",
  "Apoc Time",
  "Blocky Dimension",
  "Green RPG",
  "Construct Assault",
  "Modded Nation",
  "Super Galaxy",
  "Archer Realms",
  "Place Wars",
  "Post-Apocalyptic Bukkit",
  "High-Tech Wars",
  "Desert Survival",
  "Combat Bukkit",
  "Sparta Galaxy",
  "Waffle Outpost",
  "Tree Worlds",
  "Dawn Warzone",
  "Deadly Town",
  "Evil Gasm",
  "Winter Universe",
  "Robot Adventures",
  "Twilight Haven",
  "Dangerous Galaxy",
  "Simple Roleplay",
  "Apocalyptic CTF",
  "Noble Haven",
  "Massacre Town",
  "Bedrock Lands",
  "Apocalypse PvE",
  "RPG Lands",
  "Hell PvE",
  "Standard Haven",
  "Shelter Craft",
  "Supernatural City",
  "Supernatural Survival",
  "Danger Legends",
  "RPG Build",
  "Blocky Bukkit",
  "Archer Clan",
  "Prison Universe",
  "Shelter Tekkit",
  "Undead Adventures",
  "Electronic Realms",
  "Infinity Creative",
  "Mine PvP/Raid",
  "Mine Vanilla",
  "Noble Hardcore",
  "High-Tech Worlds",
  "Faction Gasm",
  "Warrior Kingdoms",
  "FPS Survival",
  "Tech MC",
  "Spartans Hell",
  "Metro Roleplay",
  "Chaos PvE",
  "Unlimited Games",
  "Nether World",
  "Creeper Land",
  "My World",
  "Evil Games",
  "Magma Worlds",
  "Universe Lands",
  "Super City",
  "Infinite Craft",
  "Massacre Club",
  "Apocalypse Nation",
  "Pork Army",
  "Super Empire",
  "Wood Land",
  "Redstone Legends",
  "Factory Outpost",
  "Hunt City",
  "Massacre Universe",
  "Spooky Haven",
  "Waffle RPG",
  "Place Clan",
  "Unknown Server",
  "Sandstone Factions",
  "Pancake Society",
  "Murder Scape",
  "Stone Galaxy",
  "Best sVanilla",
  "Brutal Realm",
  "Redstone Lands",
  "Construct Games",
  "Hope Mine",
  "Reflex Town",
  "Infinite Outpost",
  "Bedrock Server",
  "Epicness Survival"
]

export let countryNames = [
  "Bangladesh",
  "Belgium",
  "Burkina Faso",
  "Bulgaria",
  "Bosnia and Herzegovina",
  "Barbados",
  "Wallis and Futuna",
  "Saint Barthelemy",
  "Bermuda",
  "Brunei",
  "Bolivia",
  "Bahrain",
  "Burundi",
  "Benin",
  "Bhutan",
  "Jamaica",
  "Bouvet Island",
  "Botswana",
  "Samoa",
  "Bonaire, Saint Eustatius and Saba ",
  "Brazil",
  "Bahamas",
  "Jersey",
  "Belarus",
  "Belize",
  "Russia",
  "Rwanda",
  "Serbia",
  "East Timor",
  "Reunion",
  "Turkmenistan",
  "Tajikistan",
  "Romania",
  "Tokelau",
  "Guinea-Bissau",
  "Guam",
  "Guatemala",
  "South Georgia and the South Sandwich Islands",
  "Greece",
  "Equatorial Guinea",
  "Guadeloupe",
  "Japan",
  "Guyana",
  "Guernsey",
  "French Guiana",
  "Georgia",
  "Grenada",
  "United Kingdom",
  "Gabon",
  "El Salvador",
  "Guinea",
  "Gambia",
  "Greenland",
  "Gibraltar",
  "Ghana",
  "Oman",
  "Tunisia",
  "Jordan",
  "Croatia",
  "Haiti",
  "Hungary",
  "Hong Kong",
  "Honduras",
  "Heard Island and McDonald Islands",
  "Venezuela",
  "Puerto Rico",
  "Palestinian Territory",
  "Palau",
  "Portugal",
  "Svalbard and Jan Mayen",
  "Paraguay",
  "Iraq",
  "Panama",
  "French Polynesia",
  "Papua New Guinea",
  "Peru",
  "Pakistan",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Saint Pierre and Miquelon",
  "Zambia",
  "Western Sahara",
  "Estonia",
  "Egypt",
  "South Africa",
  "Ecuador",
  "Italy",
  "Vietnam",
  "Solomon Islands",
  "Ethiopia",
  "Somalia",
  "Zimbabwe",
  "Saudi Arabia",
  "Spain",
  "Eritrea",
  "Montenegro",
  "Moldova",
  "Madagascar",
  "Saint Martin",
  "Morocco",
  "Monaco",
  "Uzbekistan",
  "Myanmar",
  "Mali",
  "Macao",
  "Mongolia",
  "Marshall Islands",
  "Macedonia",
  "Mauritius",
  "Malta",
  "Malawi",
  "Maldives",
  "Martinique",
  "Northern Mariana Islands",
  "Montserrat",
  "Mauritania",
  "Isle of Man",
  "Uganda",
  "Tanzania",
  "Malaysia",
  "Mexico",
  "Israel",
  "France",
  "British Indian Ocean Territory",
  "Saint Helena",
  "Finland",
  "Fiji",
  "Falkland Islands",
  "Micronesia",
  "Faroe Islands",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Namibia",
  "Vanuatu",
  "New Caledonia",
  "Niger",
  "Norfolk Island",
  "Nigeria",
  "New Zealand",
  "Nepal",
  "Nauru",
  "Niue",
  "Cook Islands",
  "Kosovo",
  "Ivory Coast",
  "Switzerland",
  "Colombia",
  "China",
  "Cameroon",
  "Chile",
  "Cocos Islands",
  "Canada",
  "Republic of the Congo",
  "Central African Republic",
  "Democratic Republic of the Congo",
  "Czech Republic",
  "Cyprus",
  "Christmas Island",
  "Costa Rica",
  "Curacao",
  "Cape Verde",
  "Cuba",
  "Swaziland",
  "Syria",
  "Sint Maarten",
  "Kyrgyzstan",
  "Kenya",
  "South Sudan",
  "Suriname",
  "Kiribati",
  "Cambodia",
  "Saint Kitts and Nevis",
  "Comoros",
  "Sao Tome and Principe",
  "Slovakia",
  "South Korea",
  "Slovenia",
  "North Korea",
  "Kuwait",
  "Senegal",
  "San Marino",
  "Sierra Leone",
  "Seychelles",
  "Kazakhstan",
  "Cayman Islands",
  "Singapore",
  "Sweden",
  "Sudan",
  "Dominican Republic",
  "Dominica",
  "Djibouti",
  "Denmark",
  "British Virgin Islands",
  "Germany",
  "Yemen",
  "Algeria",
  "United States",
  "Uruguay",
  "Mayotte",
  "United States Minor Outlying Islands",
  "Lebanon",
  "Saint Lucia",
  "Laos",
  "Tuvalu",
  "Taiwan",
  "Trinidad and Tobago",
  "Turkey",
  "Sri Lanka",
  "Liechtenstein",
  "Latvia",
  "Tonga",
  "Lithuania",
  "Luxembourg",
  "Liberia",
  "Lesotho",
  "Thailand",
  "French Southern Territories",
  "Togo",
  "Chad",
  "Turks and Caicos Islands",
  "Libya",
  "Vatican",
  "Saint Vincent and the Grenadines",
  "United Arab Emirates",
  "Andorra",
  "Antigua and Barbuda",
  "Afghanistan",
  "Anguilla",
  "U.S. Virgin Islands",
  "Iceland",
  "Iran",
  "Armenia",
  "Albania",
  "Angola",
  "Antarctica",
  "American Samoa",
  "Argentina",
  "Australia",
  "Austria",
  "Aruba",
  "India",
  "Aland Islands",
  "Azerbaijan",
  "Ireland",
  "Indonesia",
  "Ukraine",
  "Qatar",
  "Mozambique"
]